Fixed import errors and updated to support python 3
scorelab/DroneSym pull request #120
Opened 2018-11-04 20:49 UTC by rohancl

- Imported queue as queue to avoid import error

![import](https://user-images.githubusercontent.com/29266591/47969668-19158f80-e0a1-11e8-8ebd-4292538e4bc2.png)

- Enabled backward compatible flask server. Did this by adding parenthesis around every print command in dronepool.py

2018-12-03 13:43 UTC, rohancl commented
Earlier:

![ree](https://user-images.githubusercontent.com/29266591/49377191-7ac42a80-f72f-11e8-8b59-c15f18e9c6f8.png)

Now:

![ree 2](https://user-images.githubusercontent.com/29266591/49377210-87e11980-f72f-11e8-988c-2e8dc955f20e.png)

2018-12-03 14:18 UTC, rohancl commented
@OshanIvantha   What do you think of the changes ?

2018-12-10 00:47 UTC, rohancl commented
## End to End test for feature - [LogIn Authorization]<br> + Login Vulnerability Test
In the recent end to end testing of DroneSym, I wrote tests for ensuring URL protection by redirections and making sure that the login system works with both, user's and admin's credentials. Logged in and out several times, in different ways to ensure  security, the functioning of Login's UI and proper authorization.

## A look


![ezgif com-gif-maker 1](https://user-images.githubusercontent.com/29266591/49705213-0a436f00-fc43-11e8-92d5-619e9285270c.gif)

2018-12-10 00:48 UTC, rohancl commented
@OshanIvantha Please Review,
Thanks ^.^

2018-12-10 08:11 UTC, swatisingh45 reviewed
Squash your commits, please.

2018-12-10 08:15 UTC, rohancl commented
@swatisingh45 Sure, I'm on it...

2018-12-10 10:40 UTC, rohancl commented
@swatisingh45 Done.

2018-12-14 22:28 UTC, angeryrohan commented
Recently, I made the page responsive at every scale, 
The web app now works flawlessly irrespective of the screen's dimensions.
EARLIER: 

![screenshot from 2018-12-15 03-57-08](https://user-images.githubusercontent.com/29266591/50033230-8fe96500-001d-11e9-9b9f-367508f94f74.png)

NOW:

![webp net-gifmaker](https://user-images.githubusercontent.com/29266591/50033177-6a5c5b80-001d-11e9-880f-1a6c1eb8c279.gif)

2018-12-14 22:28 UTC, angeryrohan commented
@OshanIvantha Please Review ^.^

2018-12-15 03:07 UTC, agentmilindu requested changes

2018-12-15 03:07 UTC, agentmilindu commented on dronesym-frontend/src/app/login/login.component.html
> +				<div class="logo-container"><!-- -->
Do we need these `<!-- -->`?

2018-12-15 03:07 UTC, agentmilindu commented on dronesym-node/index.js
>  http.listen(3000, function(){
I think you have to use your new `port` variable here also if you really want it to be used

2018-12-15 03:07 UTC, agentmilindu commented
I see lot of files related to `WiredTiger`, do we need them?

2018-12-15 03:25 UTC, angeryrohan commented on dronesym-node/index.js
>  http.listen(3000, function(){
No we don't need these, This was just to test something.... I'll remove them right away ^.^

2018-12-15 03:26 UTC, angeryrohan commented
Sorry, that's a terrible mistake there! I'll fix it right now....

2018-12-15 08:00 UTC, rohancl commented
@agentmilindu , I have made the required changes..... 
And where exactly did you see the ```WiredTiger``` files, Please give me the location

2018-12-16 11:52 UTC, agentmilindu commented
@rohancl  See the higlighted places. Plus, I assuemm `.wt` files are also related to WildTiger.
 
![image](https://user-images.githubusercontent.com/1391468/50053212-f45c0f80-0156-11e9-8d19-3024030f9048.png)

2018-12-16 22:42 UTC, rohancl commented
@agentmilindu , Seems that that was an auto-generated file by MongoDB, Anyway I've deleted them... Have a look now ^.^

2018-12-17 18:44 UTC, agentmilindu approved these changes
LGTM

2018-12-17 18:45 UTC, agentmilindu commented
@OshanIvantha

2018-12-17 19:29 UTC, malithsen approved these changes

2018-12-18 09:01 UTC, rohancl commented
@agentmilindu @OshanIvantha @malithsen  All required code quality tests are now passing ^.^ ....

2018-12-18 18:08 UTC, ivantha requested changes
@rohancl This looks good to go. 
However can you squash the commits please? 
Also there is an unnecessary package-lock.json file created at the root.

2018-12-18 21:18 UTC, rohancl commented
Yeah, Old bad habit... Sorry
Anyway, I removed the package-lock.JSON file and squashed the commits
Thanks, ^.^
@OshanIvantha

2018-12-19 03:06 UTC, ivantha approved these changes

2018-12-19 03:07 UTC, merged